/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loansystem;

import javax.swing.UIManager;

/**
 *
 * @author cgarcia
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     * Otro comentario mas..
     */
    public Principal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelOpciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tskCliente = new com.l2fprod.common.swing.JTaskPaneGroup();
        lnkNuevoCliente = new com.l2fprod.common.swing.JLinkButton();
        lnkBuscarCliente = new com.l2fprod.common.swing.JLinkButton();
        lnkModificarCliente = new com.l2fprod.common.swing.JLinkButton();
        tskPrestamo = new com.l2fprod.common.swing.JTaskPaneGroup();
        lnkNuevoPrestamo = new com.l2fprod.common.swing.JLinkButton();
        lnkNuevoPago = new com.l2fprod.common.swing.JLinkButton();
        tskEmpresa = new com.l2fprod.common.swing.JTaskPaneGroup();
        lnkEmpresa = new com.l2fprod.common.swing.JLinkButton();
        lnkUsuarios = new com.l2fprod.common.swing.JLinkButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lnkCargo = new com.l2fprod.common.swing.JLinkButton();
        lnkMonedas = new com.l2fprod.common.swing.JLinkButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Administración de Prestamos");

        pnelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        pnelOpciones.setPreferredSize(new java.awt.Dimension(220, 545));
        com.l2fprod.common.swing.PercentLayout percentLayout3 = new com.l2fprod.common.swing.PercentLayout();
        percentLayout3.setOrientation(1);
        percentLayout3.setGap(20);
        pnelOpciones.setLayout(percentLayout3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Loan System");
        pnelOpciones.add(jLabel2);

        tskCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/cliente.png"))); // NOI18N
        tskCliente.setTitle("Clientes");
        tskCliente.setOpaque(true);

        lnkNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/nuevo_cliente.png"))); // NOI18N
        lnkNuevoCliente.setText("Registrar Nuevo Ciente");
        tskCliente.getContentPane().add(lnkNuevoCliente);

        lnkBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/buscar_cliente.png"))); // NOI18N
        lnkBuscarCliente.setText("Buscar Cliente");
        tskCliente.getContentPane().add(lnkBuscarCliente);

        lnkModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/modificar_cliente.png"))); // NOI18N
        lnkModificarCliente.setText("Modificar Cliente");
        tskCliente.getContentPane().add(lnkModificarCliente);

        pnelOpciones.add(tskCliente);

        tskPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/prestamo.png"))); // NOI18N
        tskPrestamo.setTitle("Préstamo");

        lnkNuevoPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/registrar_prestamo.png"))); // NOI18N
        lnkNuevoPrestamo.setText("Registrar Préstamo");
        lnkNuevoPrestamo.setToolTipText("Registrar Nuevo Préstamo");
        lnkNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnkNuevoPrestamoActionPerformed(evt);
            }
        });
        tskPrestamo.getContentPane().add(lnkNuevoPrestamo);

        lnkNuevoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/pago.png"))); // NOI18N
        lnkNuevoPago.setText("Registrar Pago");
        tskPrestamo.getContentPane().add(lnkNuevoPago);

        pnelOpciones.add(tskPrestamo);

        tskEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/admin.png"))); // NOI18N
        tskEmpresa.setTitle("Administración");

        lnkEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/empresa.png"))); // NOI18N
        lnkEmpresa.setText("Empresa");
        tskEmpresa.getContentPane().add(lnkEmpresa);

        lnkUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/usuarios.png"))); // NOI18N
        lnkUsuarios.setText("Administrar Usuarios");
        tskEmpresa.getContentPane().add(lnkUsuarios);

        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        tskEmpresa.getContentPane().add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Catálogos");
        tskEmpresa.getContentPane().add(jLabel1);

        lnkCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/cargo.png"))); // NOI18N
        lnkCargo.setText("Cargos");
        tskEmpresa.getContentPane().add(lnkCargo);

        lnkMonedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/monedas.png"))); // NOI18N
        lnkMonedas.setText("Monedas");
        tskEmpresa.getContentPane().add(lnkMonedas);

        pnelOpciones.add(tskEmpresa);

        getContentPane().add(pnelOpciones, java.awt.BorderLayout.WEST);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/nuevo_cliente.png"))); // NOI18N
        jButton1.setToolTipText("Nuevo Cliente");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator2);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/registrar_prestamo.png"))); // NOI18N
        jButton2.setToolTipText("Nuevo Préstamo");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/pago.png"))); // NOI18N
        jButton3.setToolTipText("Registrar Pago");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/usuarios.png"))); // NOI18N
        jButton4.setToolTipText("Administrar Usuarios");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        mnuArchivo.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuClientes.setText("Clientes");
        jMenuBar1.add(mnuClientes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnkNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnkNuevoPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnkNuevoPrestamoActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private com.l2fprod.common.swing.JLinkButton lnkBuscarCliente;
    private com.l2fprod.common.swing.JLinkButton lnkCargo;
    private com.l2fprod.common.swing.JLinkButton lnkEmpresa;
    private com.l2fprod.common.swing.JLinkButton lnkModificarCliente;
    private com.l2fprod.common.swing.JLinkButton lnkMonedas;
    private com.l2fprod.common.swing.JLinkButton lnkNuevoCliente;
    private com.l2fprod.common.swing.JLinkButton lnkNuevoPago;
    private com.l2fprod.common.swing.JLinkButton lnkNuevoPrestamo;
    private com.l2fprod.common.swing.JLinkButton lnkUsuarios;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPanel pnelOpciones;
    private com.l2fprod.common.swing.JTaskPaneGroup tskCliente;
    private com.l2fprod.common.swing.JTaskPaneGroup tskEmpresa;
    private com.l2fprod.common.swing.JTaskPaneGroup tskPrestamo;
    // End of variables declaration//GEN-END:variables
}
