/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loansystem.visual.panel;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import loansystem.Principal;
import loansystem.bd.Conexion;
import loansystem.dao.ClienteDAO;
import loansystem.entidad.ClienteEntidad;
import loansystem.utilidades.MetodosGenerales;
//import loansystem.utilidades.*;

/**
 *
 * @author jechavarria
 */
public class Cliente extends javax.swing.JPanel {

    private Conexion con;
    private ClienteEntidad clieEnti;
    private ArrayList<ClienteEntidad> aClieEnti;

    private ClienteDAO clieDAO;
    private Principal prin;
    private boolean nuevo = false, modificar = false;
    private MetodosGenerales util;

    /**
     * Creates new form Cliente
     *
     * @param con
     * @param prin
     */
    public Cliente(Conexion con, Principal prin) {
        initComponents();
        this.con = con;
        this.prin = prin;
        clieDAO = new ClienteDAO(con.getCon());

        util = new MetodosGenerales();
        util.soloNumeroSinPoint(txtId);
        util.soloNumero(txtLimiteCredito);
        aClieEnti = clieDAO.obtenerTodosClientes();
        cargarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCed = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarTodos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JFormattedTextField();
        cboSexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboMunicipio = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireSec = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDirePrin = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLimiteCredito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefonoCasa = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMovil = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTelefUno = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefoDos = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        cboRuta = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTeleLabo = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtcentroLabo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        tabClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Cédula", "Sexo", "Municipio", "Movil", "Telefono", "Ruta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabClientesFocusGained(evt);
            }
        });
        tabClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabClientes);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda por:"));

        jLabel21.setText("Id:");

        jLabel22.setText("Nombres");

        try {
            txtCed.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel23.setText("Cedula:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/buscar_cliente.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscarTodos.setText("Todos");
        btnBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(8, 8, 8)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(13, 13, 13)
                        .addComponent(txtCed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnBuscarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txtCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLabel1.setText("Id:");

        jLabel2.setText("Nombres:");

        txtId2.setEditable(false);

        txtNombres.setEditable(false);

        jLabel3.setText("Apellidos:");

        txtApellidos.setEditable(false);

        jLabel4.setText("Cedula:");

        jLabel5.setText("Sexo:");

        txtCedula.setEditable(false);
        try {
            txtCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        cboSexo.setEnabled(false);

        jLabel6.setText("Municipio:");

        cboMunicipio.setEnabled(false);

        txtDireSec.setEditable(false);
        txtDireSec.setColumns(20);
        txtDireSec.setRows(5);
        jScrollPane2.setViewportView(txtDireSec);

        txtDirePrin.setEditable(false);
        txtDirePrin.setColumns(20);
        txtDirePrin.setRows(5);
        jScrollPane3.setViewportView(txtDirePrin);

        jLabel7.setText("Dirección");

        jLabel8.setText("Dirección");

        jLabel9.setText("Limite Crédito:");

        txtLimiteCredito.setEditable(false);

        jLabel11.setText("Móvil:");

        txtTelefonoCasa.setEditable(false);
        try {
            txtTelefonoCasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("Telefono Casa:");

        txtMovil.setEditable(false);
        try {
            txtMovil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovilActionPerformed(evt);
            }
        });

        jLabel13.setText("Telefono #1:");

        txtTelefUno.setEditable(false);
        try {
            txtTelefUno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setText("Telefono #2:");

        txtTelefoDos.setEditable(false);
        try {
            txtTelefoDos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setText("Ruta:");

        cboRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruta1", "Ruta2" }));
        cboRuta.setEnabled(false);

        jLabel19.setText("Principal:");

        jLabel20.setText("Sec:");

        jLabel16.setText("Centro  Laboral:");

        jLabel15.setText("Telefono Labo");

        txtTeleLabo.setEditable(false);

        jLabel18.setText("Fecha Alta:");

        txtcentroLabo.setEditable(false);

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        txtFecha.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLabel18)
                .addGap(35, 35, 35)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jLabel9)
                .addGap(21, 21, 21)
                .addComponent(txtLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(62, 62, 62)
                .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLabel13)
                .addGap(27, 27, 27)
                .addComponent(txtTelefUno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(cboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(17, 17, 17)
                .addComponent(txtTelefonoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addComponent(txtTelefoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel20))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcentroLabo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeleLabo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(664, 664, 664)
                .addComponent(btnNuevo)
                .addGap(17, 17, 17)
                .addComponent(btnModificar)
                .addGap(25, 25, 25)
                .addComponent(btnSave))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtTelefoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtTelefonoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcentroLabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtTeleLabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cboRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnSave)))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (txtId.getText().length() > 0 && txtNombre.getText().length() > 0 && txtCed.getText().length() > 0) {
//Buscar por los tres parametros
            aClieEnti = clieDAO.obtenereClientesNombreIDCed(txtNombre.getText(), txtCed.getText(), Integer.valueOf(txtId.getText()));
        } else if (txtId.getText().length() > 0) {
            //Buscar por ID
            aClieEnti = clieDAO.obtenerXCliente(Integer.valueOf(txtId.getText()));

        } else if (txtNombre.getText().length() > 0) {
            //Buscar por nombre
            aClieEnti = clieDAO.obtenereClientesNombre(txtNombre.getText());
        } else if (txtCed.getText().length() > 0 && !txtCed.getText().equals("   -      -     ")) {
            //Buscar por cedula
            aClieEnti = clieDAO.obtenerXCliente(txtCed.getText());
        } else //NO hay parametros de busqueda
        {
            if (txtCed.getText().equals("   -      -     ")) {
                JOptionPane.showMessageDialog(null, "Debe indicar al menos un parámetro de búsqueda", "Loan System", JOptionPane.ERROR_MESSAGE);
            }
        }

        /*   if (txtId.getText().equals("") && txtNombre.getText().equals("") && txtCed.getText().equals("")) {
             JOptionPane.showMessageDialog(null, "Debe indicar al menos un parámetro de búsqueda", "Loan System", JOptionPane.ERROR_MESSAGE);
         }*/
        cargarTablaClientes();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodosActionPerformed
        // TODO add your handling code here:

        aClieEnti = clieDAO.obtenerTodosClientes();
        cargarTablaClientes();

    }//GEN-LAST:event_btnBuscarTodosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtCed.setText("");
        txtNombre.setText("");
        util.limpiarTabla(tabClientes);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar_form();
        limpiar_form();
        nuevo = true;
        btnSave.setEnabled(true);
        btnModificar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        habilitar_form();
        modificar = true;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //System.out.println("********Valor " + txtTelefono.getText().substring(0,1)) ;
        /* if (txtNombres.getText().length() < 0 || txtNombres.getText().equals("")
                || txtApellidos.getText().length() < 0 || txtApellidos.getText().equals("")
                || txtCedula.getText().length() < 0 || txtCedula.getText().equals("")
                || txtMovil.getText().length() < 0 || txtMovil.getText().equals("")
                || txtFecha.getText().length() < 0 || txtFecha.getText().equals("")
                || txtDirePrin.getText().length() < 0 || txtDirePrin.getText().equals("")
                || cboMunicipio.getSelectedItem().toString().length() < 0
                || cboRuta.getSelectedItem().toString().length() < 0
                || cboSexo.getSelectedItem().toString().length() < 0) {
            JOptionPane.showMessageDialog(this, "Lo sentimos, debe ingresar datos obligatorios!!", "Catalogo de Clientes",
                    JOptionPane.ERROR_MESSAGE);
        } else {

                /**
                 * ******************************
                 * insertar nuevo cliente
                 *
               
                
                if (nuevo) {
                    save = daoClie.insertarCliente(setDatos());
                    if (save) {

                        entiClie = daoClie.obtenerUltimoIdInsertado();
                        txtCod.setText(String.valueOf(entiClie.getId_cliente()));
                        JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente!!", "Catalogo de Clientes", JOptionPane.INFORMATION_MESSAGE);
                        deshabilitar_form();
                        nuevo = false;
                        entiCliente = daoClie.obtenereTodosClientes();
                        cargarTabla();
                    } else {
                        JOptionPane.showMessageDialog(this, "Lo sentimos no se regitró el cliente!!", "Catalogo de Clientes", JOptionPane.ERROR_MESSAGE);
                    }

                }

                /**
                 * ******************************
                 * modificar cliente
                 *
                if (modificar) {
                    System.out.println("*********************Entra la if de modificar");
                    int id = Integer.parseInt(txtCod.getText());
                    save = daoClie.updateCliente(setDatos(), id);
                    if (save) {
                        JOptionPane.showMessageDialog(this, "Cliente actualizado exitosamente!!", "Catalogo de Clientes", JOptionPane.INFORMATION_MESSAGE);
                        deshabilitar_form();
                        modificar = false;
                        entiCliente = daoClie.obtenereTodosClientes();
                        cargarTabla();
                    }

                }

            }
         */
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovilActionPerformed

    private void tabClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClientesMouseClicked
        // TODO add your handling code here:
        cargarFormulario();
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tabClientesMouseClicked

    private void tabClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabClientesFocusGained
        // TODO add your handling code here:
        cargarFormulario();
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_tabClientesFocusGained

    public void cargarTablaClientes() {
        if (aClieEnti != null) {

            util.limpiarTabla(tabClientes);
            String estado;
            for (int i = 0; i < aClieEnti.size(); i++) {
                util.agregarFila(tabClientes);
                tabClientes.setValueAt(aClieEnti.get(i).getIdCliente(), i, 0); //ID
                tabClientes.setValueAt(aClieEnti.get(i).getNombres(), i, 1); //nombres
                tabClientes.setValueAt(aClieEnti.get(i).getApellidos(), i, 2); //apellidios
                tabClientes.setValueAt(aClieEnti.get(i).getNumCedula(), i, 3); //cedula
                tabClientes.setValueAt(aClieEnti.get(i).getSexo(), i, 4); //sexo
                tabClientes.setValueAt(aClieEnti.get(i).getIdMunicipio(), i, 5); //municipio
                tabClientes.setValueAt(aClieEnti.get(i).getTelefonoMovil(), i, 6); //movil
                tabClientes.setValueAt(aClieEnti.get(i).getTelefonoCasa(), i, 7); //telefono
                tabClientes.setValueAt(aClieEnti.get(i).getIdRutaVisita(), i, 8); //ruta

            }

        }
    }

    void cargarFormulario() {
        int row = tabClientes.getSelectedRow();
        //cargarCboPresentacion();
        if (tabClientes.getValueAt(row, 0) != null) {
            int id_cliente = Integer.parseInt(tabClientes.getValueAt(row, 0).toString());
            //obtener toda la info del cliente
            clieEnti = clieDAO.obtenerCliente(id_cliente);

            txtId2.setText(String.valueOf(clieEnti.getIdCliente()));
            txtNombres.setText(clieEnti.getNombres());
            txtApellidos.setText(clieEnti.getApellidos());
            txtCedula.setText(clieEnti.getNumCedula());
            txtDirePrin.setText(clieEnti.getDireccionPrincipal());
            txtDireSec.setText(clieEnti.getDireccionSecundaria());
            txtFecha.setText(clieEnti.getFechaAlta());
            txtLimiteCredito.setText(String.valueOf(clieEnti.getLimiteCredito()));
            txtMovil.setText(clieEnti.getTelefonoMovil());
            txtTeleLabo.setText(clieEnti.getTelefonoLaboral());
            txtTelefUno.setText(clieEnti.getTelefonoVario_dos());
            txtTelefoDos.setText(clieEnti.getTelefonoVario_uno());
            txtTelefonoCasa.setText(clieEnti.getTelefonoCasa());
            txtcentroLabo.setText(clieEnti.getCentroLaboral());
            
      
            
        }
    }

    void deshabilitar_form() {
        txtApellidos.setEditable(false);
        txtCedula.setEditable(false);

        txtDirePrin.setEditable(false);
        txtDireSec.setEditable(false);
        txtLimiteCredito.setEditable(false);
        txtMovil.setEditable(false);
        txtNombres.setEditable(false);
        txtTeleLabo.setEditable(false);
        txtTelefUno.setEditable(false);
        txtTelefoDos.setEditable(false);
        txtTelefonoCasa.setEditable(false);
        txtcentroLabo.setEditable(false);
        cboMunicipio.setEditable(false);
        cboRuta.setEditable(false);
        cboSexo.setEditable(false);
    }

    void habilitar_form() {
        txtApellidos.setEditable(true);
        txtCedula.setEditable(true);

        txtDirePrin.setEditable(true);
        txtDireSec.setEditable(true);
        txtLimiteCredito.setEditable(true);
        txtMovil.setEditable(true);
        txtNombres.setEditable(true);
        txtTeleLabo.setEditable(true);
        txtTelefUno.setEditable(true);
        txtTelefoDos.setEditable(true);
        txtTelefonoCasa.setEditable(true);
        txtcentroLabo.setEditable(true);
        cboMunicipio.setEditable(false);
        cboRuta.setEditable(true);
        cboSexo.setEditable(true);

    }

    void limpiar_form() {
        txtApellidos.setText("");
        txtCedula.setText("");

        txtDirePrin.setText("");
        txtDireSec.setText("");
        txtLimiteCredito.setText("");
        txtMovil.setText("");
        txtNombres.setText("");
        txtTeleLabo.setText("");
        txtTelefUno.setText("");
        txtTelefoDos.setText("");
        txtTelefonoCasa.setText("");
        txtcentroLabo.setText("");
        /*cboMunicipio.setEditable(false);
        cboRuta.setEditable(true);
        cboSexo.setEditable(true);*/

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarTodos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboMunicipio;
    private javax.swing.JComboBox<String> cboRuta;
    private javax.swing.JComboBox<String> cboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabClientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JFormattedTextField txtCed;
    private javax.swing.JFormattedTextField txtCedula;
    private javax.swing.JTextArea txtDirePrin;
    private javax.swing.JTextArea txtDireSec;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtLimiteCredito;
    private javax.swing.JFormattedTextField txtMovil;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JFormattedTextField txtTeleLabo;
    private javax.swing.JFormattedTextField txtTelefUno;
    private javax.swing.JFormattedTextField txtTelefoDos;
    private javax.swing.JFormattedTextField txtTelefonoCasa;
    private javax.swing.JTextField txtcentroLabo;
    // End of variables declaration//GEN-END:variables
}
