/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loansystem.visual.panel;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import loansystem.Principal;
import loansystem.bd.Conexion;
import loansystem.dao.ClienteDAO;
import loansystem.dao.MunicipioDAO;
import loansystem.entidad.ClienteEntidad;
import loansystem.entidad.MunicipioEntidad;
import loansystem.utilidades.MetodosGenerales;
//import loansystem.utilidades.*;

/**
 *
 * @author jechavarria
 */
public class Cliente extends javax.swing.JPanel {

    private Conexion con;
    private ClienteEntidad clieEnti;
    private ArrayList<ClienteEntidad> aClieEnti;
    MunicipioEntidad entiMun;
    MunicipioDAO daoMuni;
    private ClienteDAO clieDAO;
    private Principal prin;
    private boolean nuevo = false, modificar = false, save=false;
    private MetodosGenerales util;
    SimpleDateFormat format ;

    /**
     * Creates new form Cliente
     *
     * @param con
     * @param prin
     */
    public Cliente(Conexion con, Principal prin) {
        initComponents();
        this.con = con;
        this.prin = prin;
        clieDAO = new ClienteDAO(con.getCon());
        daoMuni = new MunicipioDAO(con.getCon());
         format = new SimpleDateFormat("dd/MM/yyyy");  
        util = new MetodosGenerales();
        util.soloNumeroSinPoint(txtId);
        util.soloNumero(txtLimiteCredito);
        aClieEnti = clieDAO.obtenerTodosClientes();
        cargarTablaClientes();
         cargarcboDepto();
    
        btnModificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelContenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCed = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnBuscarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JFormattedTextField();
        cboSexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboMunicipio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtLimiteCredito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefonoCasa = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMovil = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTelefUno = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefoDos = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTeleLabo = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtcentroLabo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboDepto = new javax.swing.JComboBox<>();
        pnlDireccion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDirePrin = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireSec = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnelContenedor.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda por:"));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Id:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Nombres:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        try {
            txtCed.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Cedula:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/botones/encontrar.png"))); // NOI18N
        btnBuscar.setToolTipText("Realizar Búsqueda");
        btnBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/botones/repeat.png"))); // NOI18N
        btnBuscarTodos.setToolTipText("Todos");
        btnBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodosActionPerformed(evt);
            }
        });

        tabClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Cédula", "Sexo", "Departamento", "Municipio", "Movil", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabClientesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabClientes);
        if (tabClientes.getColumnModel().getColumnCount() > 0) {
            tabClientes.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabClientes.getColumnModel().getColumn(1).setPreferredWidth(120);
            tabClientes.getColumnModel().getColumn(2).setPreferredWidth(120);
            tabClientes.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(txtCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar)
                            .addComponent(btnBuscarTodos))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.add(jPanel3);

        pnelContenedor.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("* Nombres:");

        txtId2.setEditable(false);
        txtId2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtNombres.setEditable(false);
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("* Apellidos:");

        txtApellidos.setEditable(false);
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidosKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("* Cedula:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("* Sexo:");

        txtCedula.setEditable(false);
        try {
            txtCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEMENINO", "MASCULINO" }));
        cboSexo.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("* Municipio:");

        cboMunicipio.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Limite Crédito:");

        txtLimiteCredito.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("* Móvil:");

        txtTelefonoCasa.setEditable(false);
        try {
            txtTelefonoCasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Telefono Casa:");

        txtMovil.setEditable(false);
        try {
            txtMovil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovilActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Telefono #1:");

        txtTelefUno.setEditable(false);
        try {
            txtTelefUno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Telefono #2:");

        txtTelefoDos.setEditable(false);
        try {
            txtTelefoDos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Centro  Laboral:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Telefono Labo");

        txtTeleLabo.setEditable(false);
        try {
            txtTeleLabo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Fecha Alta:");

        txtcentroLabo.setEditable(false);
        txtcentroLabo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcentroLaboKeyReleased(evt);
            }
        });

        txtFecha.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("* Departamento:");

        cboDepto.setEnabled(false);
        cboDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDeptoActionPerformed(evt);
            }
        });

        pnlDireccion.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("* Dirección");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Principal:");

        txtDirePrin.setEditable(false);
        txtDirePrin.setColumns(20);
        txtDirePrin.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtDirePrin.setLineWrap(true);
        txtDirePrin.setRows(5);
        txtDirePrin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDirePrinKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txtDirePrin);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Dirección");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Secundaria:");

        txtDireSec.setEditable(false);
        txtDireSec.setColumns(20);
        txtDireSec.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtDireSec.setLineWrap(true);
        txtDireSec.setRows(5);
        txtDireSec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireSecKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtDireSec);

        javax.swing.GroupLayout pnlDireccionLayout = new javax.swing.GroupLayout(pnlDireccion);
        pnlDireccion.setLayout(pnlDireccionLayout);
        pnlDireccionLayout.setHorizontalGroup(
            pnlDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireccionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDireccionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pnlDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlDireccionLayout.setVerticalGroup(
            pnlDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addGroup(pnlDireccionLayout.createSequentialGroup()
                        .addGroup(pnlDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDireccionLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel20))
                            .addGroup(pnlDireccionLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel19)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtcentroLabo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTeleLabo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefUno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(cboDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12))
                            .addComponent(txtTelefonoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13))
                            .addComponent(txtTelefUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTelefoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtTeleLabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcentroLabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(pnlDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnelContenedor.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        add(pnelContenedor, java.awt.BorderLayout.CENTER);

        lblTitulo.setBackground(new java.awt.Color(0, 0, 102));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CATALOGO DE CLIENTES");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo.setFocusable(false);
        lblTitulo.setIconTextGap(10);
        lblTitulo.setMaximumSize(new java.awt.Dimension(178, 20));
        lblTitulo.setMinimumSize(new java.awt.Dimension(178, 28));
        lblTitulo.setOpaque(true);
        lblTitulo.setPreferredSize(new java.awt.Dimension(178, 28));
        add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/nuevo.png"))); // NOI18N
        btnNuevo.setToolTipText("Nuevo Cliente");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setOpaque(false);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/modificar_cliente.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar Datos del Clietne");
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setOpaque(false);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificar);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/save.png"))); // NOI18N
        btnSave.setToolTipText("Guardar Datos del Cliente");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setOpaque(false);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/printer.png"))); // NOI18N
        btnImprimir.setToolTipText("Cancelar");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setOpaque(false);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimir);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/cerrar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setOpaque(false);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        add(jToolBar1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (txtId.getText().length() > 0 && txtNombre.getText().length() > 0 && txtCed.getText().length() > 0) {
//Buscar por los tres parametros
            aClieEnti = clieDAO.obtenereClientesNombreIDCed(txtNombre.getText(), txtCed.getText(), Integer.valueOf(txtId.getText()));
        } else if (txtId.getText().length() > 0) {
            //Buscar por ID
            aClieEnti = clieDAO.obtenerXCliente(Integer.valueOf(txtId.getText()));

        } else if (txtNombre.getText().length() > 0) {
            //Buscar por nombre
            aClieEnti = clieDAO.obtenereClientesNombre(txtNombre.getText());
        } else if (txtCed.getText().length() > 0 && !txtCed.getText().equals("   -      -     ")) {
            //Buscar por cedula
            aClieEnti = clieDAO.obtenerXCliente(txtCed.getText());
        } else //NO hay parametros de busqueda
        {
            if (txtCed.getText().equals("   -      -     ")) {
                JOptionPane.showMessageDialog(null, "Debe indicar al menos un parámetro de búsqueda", "Loan System", JOptionPane.ERROR_MESSAGE);
            }
        }

        /*   if (txtId.getText().equals("") && txtNombre.getText().equals("") && txtCed.getText().equals("")) {
             JOptionPane.showMessageDialog(null, "Debe indicar al menos un parámetro de búsqueda", "Loan System", JOptionPane.ERROR_MESSAGE);
         }*/
        cargarTablaClientes();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodosActionPerformed
        // TODO add your handling code here:

        aClieEnti = clieDAO.obtenerTodosClientes();
        cargarTablaClientes();
 txtId.setText("");
        txtCed.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_btnBuscarTodosActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        
        habilitar_form();
        limpiar_form();
        nuevo = true;
        btnSave.setEnabled(true);
        btnModificar.setEnabled(false);
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        habilitar_form();
        modificar = true;
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //System.out.println("********Valor " + txtTelefono.getText().substring(0,1)) ;
     if (txtNombres.getText().length() < 0 || txtNombres.getText().equals("")
                || txtApellidos.getText().length() < 0 || txtApellidos.getText().equals("")
                || txtCedula.getText().length() < 0 || txtCedula.getText().equals("   -      -     ")
                || txtMovil.getText().length() < 0 || txtMovil.getText().equals("")
               // || txtFecha.getText().length() < 0 || txtFecha.getText().equals("")
                || txtDirePrin.getText().length() < 0 || txtDirePrin.getText().equals("")
                || cboDepto.getSelectedItem().toString().length() < 0
                || cboMunicipio.getSelectedItem().toString().length() < 0
//                || cboRuta.getSelectedItem().toString().length() < 0
                || cboSexo.getSelectedItem().toString().length() < 0) {
            JOptionPane.showMessageDialog(this, "Lo sentimos, debe ingresar datos obligatorios!!", "Catalogo de Clientes",
                    JOptionPane.ERROR_MESSAGE);
        } else {

                /**
                 * ******************************
                 * insertar nuevo cliente
                 */
             
                
                if (nuevo) {
                   int id = clieDAO.insertarCliente(setDatos());
                    if (id>0) {

                    //    clieEnti = clieDAO.obtenerUltimoIdInsertado();
                        txtId2.setText(util.completarCerosID(id,6));
                                            
                       txtFecha.setText(String.valueOf(format.format(new Date())));
                       
                        JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente!!", "Catalogo de Clientes", JOptionPane.INFORMATION_MESSAGE);
                        deshabilitar_form();
                        btnSave.setEnabled(false);
                        nuevo = false;
                        aClieEnti = clieDAO.obtenerTodosClientes();
                        cargarTablaClientes();
                    } else {
                        JOptionPane.showMessageDialog(this, "Lo sentimos no se regitró el cliente!!", "Catalogo de Clientes", JOptionPane.ERROR_MESSAGE);
                    }

                }

                /**
                 * ******************************
                 * modificar cliente
                 */
                
                if (modificar) {
                    System.out.println("*********************Entra la if de modificar");
                    int id = Integer.parseInt(txtId2.getText());
                    save = clieDAO.updateCliente(setDatos(),id);
                    if (save) {
                        JOptionPane.showMessageDialog(this, "Cliente actualizado exitosamente!!", "Catalogo de Clientes", JOptionPane.INFORMATION_MESSAGE);
                        deshabilitar_form();
                        btnSave.setEnabled(false);
                         modificar = false;
                         aClieEnti = clieDAO.obtenerTodosClientes();
                         cargarTablaClientes();
                    }

                }

            }
         
    }//GEN-LAST:event_btnSaveActionPerformed

     public ClienteEntidad setDatos() {
     ClienteEntidad clieEnti;
        clieEnti = new ClienteEntidad();
        clieEnti.setApellidos(txtApellidos.getText());
        clieEnti.setCentroLaboral(txtcentroLabo.getText());
        clieEnti.setDireccionPrincipal(txtDirePrin.getText());
        clieEnti.setDireccionSecundaria(txtDireSec.getText());
        clieEnti.setIdEmpresa(1);
        MunicipioEntidad entiMun;
        MunicipioDAO daoMuni = new MunicipioDAO(con.getCon());
        entiMun = daoMuni.obtenerMunicipioXNombre(String.valueOf(cboMunicipio.getSelectedItem()));
        clieEnti.setIdMunicipio(entiMun.getIdMunicipio());
        clieEnti.setIdRutaVisita(1);
        //clieEnti.setIdDepartamento(1);
        if(txtLimiteCredito.getText().equals("")){clieEnti.setLimiteCredito(0);}
        else{   clieEnti.setLimiteCredito(Double.parseDouble(txtLimiteCredito.getText()));}
        clieEnti.setDiasCredito(0);
        clieEnti.setNombres(txtNombres.getText());
        clieEnti.setNumCedula(txtCedula.getText());
        clieEnti.setSexo(String.valueOf(cboSexo.getSelectedItem()));
        clieEnti.setTelefonoCasa(txtTelefonoCasa.getText());
        clieEnti.setTelefonoLaboral(txtTeleLabo.getText());
        clieEnti.setTelefonoMovil(txtMovil.getText());
        clieEnti.setTelefonoVario_dos(txtTelefoDos.getText());
        clieEnti.setTelefonoVario_uno(txtTelefUno.getText());
        return clieEnti; 
        
     }
     
    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovilActionPerformed

    private void tabClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClientesMouseClicked
        // TODO add your handling code here:
        cargarFormulario();
        btnModificar.setEnabled(true);
        btnSave.setEnabled(false);
    }//GEN-LAST:event_tabClientesMouseClicked

    private void cboDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDeptoActionPerformed
        // TODO add your handling code here:
        cargarcboMunicipioxDepto();
    }//GEN-LAST:event_cboDeptoActionPerformed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        // TODO add your handling code here:
         char c = evt.getKeyChar();
                if (!(Character.isDigit(c)
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE)
                        //|| (c == KeyEvent.VK_PERIOD)
                        || (c == KeyEvent.VK_ENTER))) {
                    
            String a = txtNombres.getText().toUpperCase();
            txtNombres.setText(a);
            evt.consume();}
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyReleased
        // TODO add your handling code here:
         char c = evt.getKeyChar();
                if (!(Character.isDigit(c)
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE)
                        //|| (c == KeyEvent.VK_PERIOD)
                        || (c == KeyEvent.VK_ENTER))) {
                    
            String a = txtApellidos.getText().toUpperCase();
            txtApellidos.setText(a);
            evt.consume();}
    }//GEN-LAST:event_txtApellidosKeyReleased

    private void txtDirePrinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirePrinKeyReleased
        // TODO add your handling code here:
         char c = evt.getKeyChar();
                if (!(Character.isDigit(c)
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE)
                        //|| (c == KeyEvent.VK_PERIOD)
                        || (c == KeyEvent.VK_ENTER))) {
                    
            String a = txtDirePrin.getText().toUpperCase();
            txtDirePrin.setText(a);
            evt.consume();}
    }//GEN-LAST:event_txtDirePrinKeyReleased

    private void txtDireSecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireSecKeyReleased
        // TODO add your handling code here:
         char c = evt.getKeyChar();
                if (!(Character.isDigit(c)
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE)
                        //|| (c == KeyEvent.VK_PERIOD)
                        || (c == KeyEvent.VK_ENTER))) {
                    
            String a = txtDireSec.getText().toUpperCase();
            txtDireSec.setText(a);
            evt.consume();}
    }//GEN-LAST:event_txtDireSecKeyReleased

    private void tabClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabClientesMouseEntered

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        prin.removerTab(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
       JOptionPane.showMessageDialog(prin, "Aqui va la logica para el reporte de impresion!","Imprimir datos del cliente!",JOptionPane.INFORMATION_MESSAGE,
               new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/nuevo_cliente.png")));
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtcentroLaboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcentroLaboKeyReleased
        // TODO add your handling code here:
                 char c = evt.getKeyChar();
                if (!(Character.isDigit(c)
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE)
                        //|| (c == KeyEvent.VK_PERIOD)
                        || (c == KeyEvent.VK_ENTER))) {
                    
            String a = txtNombres.getText().toUpperCase();
            txtNombres.setText(a);
            evt.consume();}
    }//GEN-LAST:event_txtcentroLaboKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if (!(Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                //|| (c == KeyEvent.VK_PERIOD)
                || (c == KeyEvent.VK_ENTER))) {

            String a = txtNombres.getText().toUpperCase();
            txtNombres.setText(a);
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    public void cargarTablaClientes() {
        if (aClieEnti != null) {

            util.limpiarTabla(tabClientes);
            String estado;
            for (int i = 0; i < aClieEnti.size(); i++) {
                util.agregarFila(tabClientes);
                tabClientes.setValueAt(aClieEnti.get(i).getIdCliente(), i, 0); //ID
                tabClientes.setValueAt(aClieEnti.get(i).getNombres(), i, 1); //nombres
                tabClientes.setValueAt(aClieEnti.get(i).getApellidos(), i, 2); //apellidios
                tabClientes.setValueAt(aClieEnti.get(i).getNumCedula(), i, 3); //cedula
                tabClientes.setValueAt(aClieEnti.get(i).getSexo(), i, 4); //sexo
                entiMun = daoMuni.obtenerMunicipioXId(aClieEnti.get(i).getIdMunicipio());
                tabClientes.setValueAt(entiMun.getDepartamento(), i, 5); //departamento
                tabClientes.setValueAt(entiMun.getMunicipio(), i, 6); //municipio
                tabClientes.setValueAt(aClieEnti.get(i).getTelefonoMovil(), i, 7); //movil
                tabClientes.setValueAt(aClieEnti.get(i).getTelefonoCasa(), i, 8); //telefono
                //tabClientes.setValueAt(aClieEnti.get(i).getIdRutaVisita(), i, 8); //ruta

            }

        }
    }

    void cargarFormulario() {
        int row = tabClientes.getSelectedRow();
        //cargarCboPresentacion();
        if (tabClientes.getValueAt(row, 0) != null) {
            int id_cliente = Integer.parseInt(tabClientes.getValueAt(row, 0).toString());
            //obtener toda la info del cliente
            clieEnti = clieDAO.obtenerCliente(id_cliente);

            txtId2.setText(util.completarCerosID(clieEnti.getIdCliente(),6));
            txtNombres.setText(clieEnti.getNombres());
            txtApellidos.setText(clieEnti.getApellidos());
            txtCedula.setText(clieEnti.getNumCedula());
            txtDirePrin.setText(clieEnti.getDireccionPrincipal());
            txtDireSec.setText(clieEnti.getDireccionSecundaria());
            txtFecha.setText(clieEnti.getFechaAlta().substring(0,10));
           // txtFecha.setText(String.valueOf(format.format(Date.clieEnti.getFechaAlta() )));
           /* DecimalFormat formato = new DecimalFormat("###,###.##");
            txtLimiteCredito.setText(String.valueOf(formato.format(clieEnti.getLimiteCredito())));*/
            txtLimiteCredito.setText(String.valueOf(clieEnti.getLimiteCredito()));
            txtMovil.setText(clieEnti.getTelefonoMovil());
            txtTeleLabo.setText(clieEnti.getTelefonoLaboral());
            txtTelefUno.setText(clieEnti.getTelefonoVario_dos());
            txtTelefoDos.setText(clieEnti.getTelefonoVario_uno());
            txtTelefonoCasa.setText(clieEnti.getTelefonoCasa());
            txtcentroLabo.setText(clieEnti.getCentroLaboral());
            
            cboSexo.setSelectedItem(clieEnti.getSexo());
           //cboRuta.setSelectedItem(clieEnti);
           int idMun = clieEnti.getIdMunicipio();
       
           entiMun = daoMuni.obtenerMunicipioXId(idMun);
           
           cboDepto.setSelectedItem(entiMun.getDepartamento());
           cboMunicipio.setSelectedItem(entiMun.getMunicipio());
           
           
           deshabilitar_form();
        }
    }

    void cargarcboDepto(){
    ArrayList<MunicipioEntidad>entiDepto;
    MunicipioDAO daoMuni = new MunicipioDAO(con.getCon());
    entiDepto = daoMuni.obtenerDeptos();
    
    for (int i= 0; i<entiDepto.size();i++){
    cboDepto.addItem(entiDepto.get(i).getDepartamento());}
    
    }
    
    void cargarcboMunicipioxDepto(){
    ArrayList<MunicipioEntidad>entiMun;
    MunicipioDAO daoMuni = new MunicipioDAO(con.getCon());
    entiMun = daoMuni.obtenerTodosxDepto(String.valueOf(cboDepto.getSelectedItem()));
    cboMunicipio.removeAllItems();
    for (int i= 0; i<entiMun.size();i++){
    cboMunicipio.addItem(entiMun.get(i).getMunicipio());}
    
    }
    
    void deshabilitar_form() {
        txtApellidos.setEditable(false);
        txtCedula.setEditable(false);

        txtDirePrin.setEditable(false);
        txtDireSec.setEditable(false);
        txtLimiteCredito.setEditable(false);
        txtMovil.setEditable(false);
        txtNombres.setEditable(false);
        txtTeleLabo.setEditable(false);
        txtTelefUno.setEditable(false);
        txtTelefoDos.setEditable(false);
        txtTelefonoCasa.setEditable(false);
        txtcentroLabo.setEditable(false);
        cboMunicipio.setEnabled(false);
        cboDepto.setEnabled(false);
//        cboRuta.setEditable(false);
        cboSexo.setEnabled(false);
    }

    void habilitar_form() {
        txtApellidos.setEditable(true);
        txtCedula.setEditable(true);

        txtDirePrin.setEditable(true);
        txtDireSec.setEditable(true);
        txtLimiteCredito.setEditable(true);
        txtMovil.setEditable(true);
        txtNombres.setEditable(true);
        txtTeleLabo.setEditable(true);
        txtTelefUno.setEditable(true);
        txtTelefoDos.setEditable(true);
        txtTelefonoCasa.setEditable(true);
        txtcentroLabo.setEditable(true);
        cboMunicipio.setEnabled(true);
//        cboRuta.setEnabled(true);
        cboSexo.setEnabled(true);
        cboDepto.setEnabled(true);
        

    }

    void limpiar_form() {
        txtId2.setText("");
        txtApellidos.setText("");
        txtCedula.setText("");

        txtDirePrin.setText("");
        txtDireSec.setText("");
        txtLimiteCredito.setText("");
        txtMovil.setText("");
        txtNombres.setText("");
        txtTeleLabo.setText("");
        txtTelefUno.setText("");
        txtTelefoDos.setText("");
        txtTelefonoCasa.setText("");
        txtcentroLabo.setText("");
        txtFecha.setText("");
        /*cboMunicipio.setEditable(false);
        cboRuta.setEditable(true);
        cboSexo.setEditable(true);*/

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarTodos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboDepto;
    private javax.swing.JComboBox<String> cboMunicipio;
    private javax.swing.JComboBox<String> cboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnelContenedor;
    private javax.swing.JPanel pnlDireccion;
    private javax.swing.JTable tabClientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JFormattedTextField txtCed;
    private javax.swing.JFormattedTextField txtCedula;
    private javax.swing.JTextArea txtDirePrin;
    private javax.swing.JTextArea txtDireSec;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtLimiteCredito;
    private javax.swing.JFormattedTextField txtMovil;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JFormattedTextField txtTeleLabo;
    private javax.swing.JFormattedTextField txtTelefUno;
    private javax.swing.JFormattedTextField txtTelefoDos;
    private javax.swing.JFormattedTextField txtTelefonoCasa;
    private javax.swing.JTextField txtcentroLabo;
    // End of variables declaration//GEN-END:variables
}
