/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loansystem.visual.panel;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import loansystem.Principal;
import loansystem.bd.Conexion;
import loansystem.dao.CuotasDAO;
import loansystem.dao.MunicipioDAO;
import loansystem.dao.PrestamoDAO;
import loansystem.entidad.ClienteEntidad;
import loansystem.entidad.CuotasEntidad;
import loansystem.entidad.MunicipioEntidad;
import loansystem.entidad.PrestamoEntidad;
import loansystem.utilidades.MetodosGenerales;
import loansystem.utilidades.NumberToLetterConverter;
import loansystem.visual.modal.BuscarCliente;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author cgarcia
 */
public class Prestamo extends javax.swing.JPanel {

    private Conexion con;
    private Principal prin;
    private MetodosGenerales util;

    double totalPrestamo = 0;
    double cuota = 0;
    int cantCuota = 0;
    String moneda = "C$";
    String descMoneda = "Córdobas";

    private ClienteEntidad cliente = null;
    private Integer cantPlazo;
    private int dias;
    private Integer cantPlazoFrec;
    private int diasFrecPago;
    private double montoPrestamo;
    private double tasaInteres;
    private double tasaCargos;
    private double montoInteres;
    private double montoCargos;
    private int idMoneda;

    /**
     * Creates new form Prestamo
     */
    public Prestamo(Conexion con, Principal prin) {
        this.con = con;
        this.prin = prin;

        initComponents();

        formatoDatePicker(this.dtFechaInicio);
        formatoDatePicker(this.dtFechaFin);
        util = new MetodosGenerales();

        //Nuevo comentario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        toolOpciones = new javax.swing.JToolBar();
        btnBuscar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnelContenedor = new javax.swing.JPanel();
        pnelCliente = new javax.swing.JPanel();
        pnelDatosCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTelefono = new javax.swing.JList<>();
        rbtnFemenino = new javax.swing.JRadioButton();
        rbtnMasculino = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtCobro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCentroLab = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDireccionPrin = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccionSec = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        scrollPrestamo = new javax.swing.JScrollPane();
        pnelPrestamo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        spnFrecuencia = new javax.swing.JSpinner();
        cboDias = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtMontoPenalidad = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        spnDiasPenalidad = new javax.swing.JSpinner();
        spnPlazo = new javax.swing.JSpinner();
        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();
        jLabel13 = new javax.swing.JLabel();
        dtFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dtFechaFin = new org.jdesktop.swingx.JXDatePicker();
        cboDiasFrec = new javax.swing.JComboBox<>();
        btnCalcular1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtMontoInteres = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        cboMoneda = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTasa = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        txtMontoPrestamo = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMontoLetras = new javax.swing.JTextField();
        txtTasaCargo = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        txtMontoCargos = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jXTitledSeparator4 = new org.jdesktop.swingx.JXTitledSeparator();
        txtTotalPrestamo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabCuotas = new javax.swing.JTable();
        jXTitledSeparator3 = new org.jdesktop.swingx.JXTitledSeparator();
        jLabel18 = new javax.swing.JLabel();
        txtCantCuotas = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCantDias = new javax.swing.JTextField();
        txtMontoCuota = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        toolOpciones.setFloatable(false);
        toolOpciones.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolOpciones.setRollover(true);
        toolOpciones.setOpaque(false);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/search.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar Cliente");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setOpaque(false);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        toolOpciones.add(btnBuscar);

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/calculator.png"))); // NOI18N
        btnCalcular.setToolTipText("Calcular");
        btnCalcular.setMaximumSize(new java.awt.Dimension(43, 43));
        btnCalcular.setMinimumSize(new java.awt.Dimension(43, 43));
        btnCalcular.setOpaque(false);
        btnCalcular.setPreferredSize(new java.awt.Dimension(43, 43));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        toolOpciones.add(btnCalcular);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/repeat.png"))); // NOI18N
        btnLimpiar.setToolTipText("Limpiar");
        btnLimpiar.setOpaque(false);
        toolOpciones.add(btnLimpiar);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/save.png"))); // NOI18N
        btnGuardar.setToolTipText("Aceptar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setOpaque(false);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        toolOpciones.add(btnGuardar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/cerrar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setOpaque(false);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        toolOpciones.add(btnCancelar);

        add(toolOpciones, java.awt.BorderLayout.WEST);

        pnelContenedor.setLayout(new java.awt.BorderLayout());

        pnelCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnelCliente.setLayout(new java.awt.BorderLayout());

        pnelDatosCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Cédula:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Nombres:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Apellidos:");

        txtApellidos.setEditable(false);

        txtNombres.setEditable(false);

        txtCedula.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Departamento:");

        txtDepartamento.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Municipio:");

        txtMunicipio.setEditable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Teléfonos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        lstTelefono.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstTelefono);

        jPanel4.add(jScrollPane1);

        buttonGroup1.add(rbtnFemenino);
        rbtnFemenino.setText("Femenino");
        rbtnFemenino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rbtnFemenino.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rbtnFemenino.setOpaque(false);

        buttonGroup1.add(rbtnMasculino);
        rbtnMasculino.setText("Masculino");
        rbtnMasculino.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Ruta Cobro:");

        txtCobro.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Centro Laboral:");

        txtCentroLab.setEditable(false);
        txtCentroLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCentroLabActionPerformed(evt);
            }
        });

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dirección Principal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane3.setOpaque(false);

        txtDireccionPrin.setEditable(false);
        txtDireccionPrin.setColumns(20);
        txtDireccionPrin.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtDireccionPrin.setLineWrap(true);
        txtDireccionPrin.setRows(5);
        jScrollPane3.setViewportView(txtDireccionPrin);

        jPanel5.add(jScrollPane3);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dirección Secundaria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane2.setOpaque(false);

        txtDireccionSec.setEditable(false);
        txtDireccionSec.setColumns(20);
        txtDireccionSec.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtDireccionSec.setLineWrap(true);
        txtDireccionSec.setRows(5);
        jScrollPane2.setViewportView(txtDireccionSec);

        jPanel5.add(jScrollPane2);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Código:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.setText("000000");

        javax.swing.GroupLayout pnelDatosClienteLayout = new javax.swing.GroupLayout(pnelDatosCliente);
        pnelDatosCliente.setLayout(pnelDatosClienteLayout);
        pnelDatosClienteLayout.setHorizontalGroup(
            pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(rbtnMasculino)
                        .addGap(333, 333, 333))
                    .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                        .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                                .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtnFemenino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombres)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtDepartamento))
                                .addGap(18, 18, 18)
                                .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtMunicipio)
                                    .addComponent(txtCobro)
                                    .addComponent(txtCedula)))
                            .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCentroLab)))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnelDatosClienteLayout.setVerticalGroup(
            pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelDatosClienteLayout.createSequentialGroup()
                        .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnFemenino)
                            .addComponent(rbtnMasculino)
                            .addComponent(jLabel10)
                            .addComponent(txtCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(pnelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCentroLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pnelCliente.add(pnelDatosCliente, java.awt.BorderLayout.CENTER);

        lblTitulo.setBackground(new java.awt.Color(0, 0, 102));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ASIGNACÓN DE PRÉSTAMO");
        lblTitulo.setOpaque(true);
        lblTitulo.setPreferredSize(new java.awt.Dimension(195, 28));
        pnelCliente.add(lblTitulo, java.awt.BorderLayout.PAGE_START);
        lblTitulo.getAccessibleContext().setAccessibleName("ASIGNACIÓN DE PRÉSTAMO");

        pnelContenedor.add(pnelCliente, java.awt.BorderLayout.NORTH);

        scrollPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        scrollPrestamo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle del Préstamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        scrollPrestamo.setAutoscrolls(true);

        pnelPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        pnelPrestamo.setAutoscrolls(true);

        jPanel1.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Plazo:");

        cboDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Mes", "Año" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Monto Penalidad:");

        txtMontoPenalidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Dias Para Penalidad:");

        jXTitledSeparator1.setForeground(new java.awt.Color(0, 51, 153));
        jXTitledSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jXTitledSeparator1.setTitle("Plazo del Péstamo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Fecha de Inicio:");

        dtFechaInicio.setToolTipText("Fecha de Inicio");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Fecha de Vencimiento:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Frecuencia de Pago:");

        dtFechaFin.setToolTipText("Fecha de Fin");
        dtFechaFin.setEditable(false);

        cboDiasFrec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Mes", "Año" }));

        btnCalcular1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/calculator.png"))); // NOI18N
        btnCalcular1.setToolTipText("Calcular Cuotas");
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboDias, 0, 119, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dtFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(201, 201, 201))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboDiasFrec, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnDiasPenalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMontoPenalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboDiasFrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnDiasPenalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontoPenalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCalcular1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Monto Solicitado:");

        txtMontoInteres.setEditable(false);
        txtMontoInteres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Moneda:");

        cboMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Córdobas", "Dólares", "Euros" }));
        cboMoneda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMonedaItemStateChanged(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("En Letras:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Tasa (%):");

        txtTasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtTasa.setText("0.0");
        txtTasa.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Monto de Interés:");

        txtMontoPrestamo.setForeground(new java.awt.Color(0, 51, 153));
        txtMontoPrestamo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtMontoPrestamo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMontoPrestamo.setName(""); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Otros Cargos (%):");

        txtMontoLetras.setEditable(false);
        txtMontoLetras.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMontoLetras.setToolTipText("");
        txtMontoLetras.setPreferredSize(new java.awt.Dimension(6, 23));

        txtTasaCargo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtTasaCargo.setText("0.0");
        txtTasaCargo.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Monto Otros Cargos:");

        txtMontoCargos.setEditable(false);
        txtMontoCargos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 153, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Total Préstamo:");

        jXTitledSeparator4.setForeground(new java.awt.Color(0, 51, 153));
        jXTitledSeparator4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jXTitledSeparator4.setTitle("Generales");

        txtTotalPrestamo.setEditable(false);
        txtTotalPrestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPrestamo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtTasaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtMontoPrestamo)
                                            .addComponent(cboMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMontoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMontoCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMontoLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jXTitledSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTasaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setOpaque(false);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Monto de Cuota:");

        tabCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Pago", "Fecha", "Dia", "Monto", "Saldo", "Cancelada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabCuotas);

        jXTitledSeparator3.setForeground(new java.awt.Color(0, 51, 153));
        jXTitledSeparator3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jXTitledSeparator3.setTitle("Detalle de Cuotas");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Cantidad Cuotas:");

        txtCantCuotas.setEditable(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Dias Totales:");

        txtCantDias.setEditable(false);

        txtMontoCuota.setEditable(false);
        txtMontoCuota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jXTitledSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtCantCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantDias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMontoCuota))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jXTitledSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCantCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtCantDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnelPrestamoLayout = new javax.swing.GroupLayout(pnelPrestamo);
        pnelPrestamo.setLayout(pnelPrestamoLayout);
        pnelPrestamoLayout.setHorizontalGroup(
            pnelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnelPrestamoLayout.setVerticalGroup(
            pnelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelPrestamoLayout.createSequentialGroup()
                .addGroup(pnelPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnelPrestamoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        scrollPrestamo.setViewportView(pnelPrestamo);

        pnelContenedor.add(scrollPrestamo, java.awt.BorderLayout.CENTER);

        add(pnelContenedor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCentroLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCentroLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCentroLabActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BuscarCliente bc = new BuscarCliente(prin, true, con, this);
        bc.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        calcularPrestamo();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        if (totalPrestamo <= 0) {
            JOptionPane.showMessageDialog(prin, "Debe calcular el préstamo primero!", "Cálculo de Préstamo!", JOptionPane.ERROR_MESSAGE);
        } else {
            calcularCuotas();

        }


    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void cboMonedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMonedaItemStateChanged
        int index = cboMoneda.getSelectedIndex();
        descMoneda = cboMoneda.getSelectedItem().toString();
        idMoneda = 0;

        switch (index) {
            case 0:
                moneda = "C$";
                idMoneda = 1;
                break;

            case 1:
                moneda = "U$";
                idMoneda = 2;
                break;

            case 2:
                moneda = "€";
                idMoneda = 3;
                break;
        }


    }//GEN-LAST:event_cboMonedaItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarPrestamo();
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void cargarDatosCliente(ClienteEntidad cliente) {
        this.cliente = cliente;

        MunicipioDAO muDao = new MunicipioDAO(con.getCon());
        MunicipioEntidad municipio = muDao.obtenerMunicipioXId(cliente.getIdMunicipio());

        this.txtNombres.setText(cliente.getNombres());
        this.txtApellidos.setText(cliente.getApellidos());
        this.txtCentroLab.setText(cliente.getCentroLaboral());
        this.txtCedula.setText(cliente.getNumCedula());
        this.txtCodigo.setText(completarCerosID(cliente.getIdCliente(), 6));
        this.txtDepartamento.setText(municipio.getDepartamento());
        this.txtMunicipio.setText(municipio.getMunicipio());
        this.txtDireccionPrin.setText(cliente.getDireccionPrincipal());
        this.txtDireccionSec.setText(cliente.getDireccionSecundaria());

        if (cliente.getSexo().equals("M")) {
            rbtnMasculino.setSelected(true);
        } else {
            rbtnFemenino.setSelected(true);
        }
        try {

            DefaultListModel modelo = new DefaultListModel();
            if (cliente.getTelefonoMovil().length() > 0) {
                modelo.addElement("Móvil:    " + cliente.getTelefonoMovil());
            }

            if (cliente.getTelefonoCasa().length() > 0) {
                modelo.addElement("Casa:     " + cliente.getTelefonoCasa());
            }

            if (cliente.getTelefonoLaboral().length() > 0) {
                modelo.addElement("Laboral:  " + cliente.getTelefonoLaboral());
            }

            if (cliente.getTelefonoVario_uno() != null) {
                modelo.addElement("Otro 1:   " + cliente.getTelefonoVario_uno());
            }

            if (cliente.getTelefonoVario_dos() != null) {
                modelo.addElement("Otro 2:   " + cliente.getTelefonoVario_dos());
            }

            lstTelefono.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     *
     * @param id
     * @param espacios
     * @return
     */
    private String completarCerosID(int id, int espacios) {
        String idStr = String.valueOf(id);
        String nuevoId = "";
        StringBuilder aux = new StringBuilder();

        if (idStr.length() < espacios) {
            for (int i = 0; i < espacios - idStr.length(); i++) {
                aux.append("0");
            }

            aux.append(idStr);
            nuevoId = aux.toString();

        } else {
            nuevoId = String.valueOf(id);
        }

        return nuevoId;
    }

    /**
     * Logica para realizar el calculo del prestamo.
     */
    private void calcularPrestamo() {
        montoPrestamo = 0;
        tasaInteres = 0;
        tasaCargos = 0;

        montoInteres = 0;
        montoCargos = 0;

        if (txtMontoPrestamo.getText().length() > 0) {
            montoPrestamo = Double.parseDouble(txtMontoPrestamo.getText().replace(",", ""));

            if (txtTasa.getText().length() > 0) {
                tasaInteres = Double.parseDouble(txtTasa.getText()) / 100;

                if (txtTasaCargo.getText().length() > 0) {
                    tasaCargos = Double.parseDouble(txtTasaCargo.getText()) / 100;
                } else {
                    tasaCargos = 0;
                }

                montoInteres = (montoPrestamo * tasaInteres);
                montoCargos = (montoPrestamo * tasaCargos);
                totalPrestamo = montoPrestamo + montoInteres + montoCargos;

                txtMontoInteres.setText(String.valueOf(formatearMoneda(montoInteres, moneda)));
                txtMontoCargos.setText(String.valueOf(formatearMoneda(montoCargos, moneda)));

                txtTotalPrestamo.setText(String.valueOf(formatearMoneda(totalPrestamo, moneda)));
                txtMontoLetras.setText(NumberToLetterConverter.convertNumberToLetter(totalPrestamo, descMoneda));

            } else {
                JOptionPane.showMessageDialog(prin, "Debe indicar la tasa de interes!", "Cálculo de Préstamo!", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(prin, "Debe indicar el monto del Prestamo!", "Cálculo de Préstamo!", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * Calculamos la cantidad de dias de un plazo
     *
     * @param plazo
     * @param cantidad
     * @return
     */
    private int calcularDiasPlazo(String plazo, int cantidad) {
        int dias = 0;

        switch (plazo) {
            case "Dia":
                dias = 1;
                break;

            case "Semana":
                dias = 7;
                break;

            case "Mes":
                dias = 30;
                break;

            case "Año":
                dias = 365;
                break;
        }

        dias = dias * cantidad;

        return dias;
    }

    /**
     *
     */
    private void calcularCuotas() {
        String plazo = cboDias.getSelectedItem().toString();
        String plazoFrec = cboDiasFrec.getSelectedItem().toString();
        cantPlazo = Integer.valueOf(spnPlazo.getValue().toString());
        dias = calcularDiasPlazo(plazo, cantPlazo);

        cantPlazoFrec = Integer.valueOf(spnFrecuencia.getValue().toString());
        diasFrecPago = calcularDiasPlazo(plazoFrec, cantPlazoFrec);

        cantCuota = dias / diasFrecPago;
        cuota = totalPrestamo / cantCuota;

        txtMontoCuota.setText(String.valueOf(formatearMoneda(round(cuota, 2), moneda)) + " por " + plazoFrec);

        int cantCuotasT = (int) round(cantCuota, 2);
        txtCantCuotas.setText(String.valueOf(round(cantCuota, 2)));
        txtCantDias.setText(String.valueOf(dias));

        Date fechaI = dtFechaInicio.getDate();

        System.out.println("Fecha seleccionada: " + fechaI.toString());

        Date fechaFin = calcularFechasPago(diasFrecPago, cantCuotasT, round(cuota, 2), fechaI, totalPrestamo);
        dtFechaFin.setDate(fechaFin);
    }

    /**
     *
     * @param dias
     * @param cuotas
     * @param montoCuota
     * @param fechaI
     */
    private Date calcularFechasPago(int dias, int cuotas, double montoCuota, Date fechaI, double totalPrestamo) {
        String[][] cuotasHash = generarFechasPago(dias, cuotas, fechaI);
        double saldoTemp = 0;
        saldoTemp = totalPrestamo;
        String fechaFin = "";

        if (cuotasHash.length > 0) {
            SimpleDateFormat formatDia = new SimpleDateFormat("EEEE");
            util.limpiarTabla(tabCuotas);
            for (int i = 0; i < cuotasHash.length; i++) {
                util.agregarFila(tabCuotas);
                saldoTemp = saldoTemp - cuota;

                tabCuotas.setValueAt("Pago " + (i + 1), i, 0); //ID
                tabCuotas.setValueAt(cuotasHash[i][0], i, 1); //ID
                tabCuotas.setValueAt(cuotasHash[i][1], i, 2); //ID
                tabCuotas.setValueAt(montoCuota, i, 3); //ID
                tabCuotas.setValueAt((round(saldoTemp, 2) < 0 ? 0 : round(saldoTemp, 2)), i, 4); //ID
                tabCuotas.setValueAt(false, i, 5);

                fechaFin = cuotasHash[i][0];
            }

        }

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha = null;
        try {
            fecha = formato.parse(fechaFin);
        } catch (ParseException ex) {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }

        return fecha;
    }

    /**
     *
     * @param value
     * @param places
     * @return
     */
    public double round(double value, int places) {
        if (places < 0) {
            throw new IllegalArgumentException();
        }

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }

    /**
     *
     * @param monto
     * @param moneda
     * @return
     */
    private String formatearMoneda(double monto, String moneda) {
        StringBuilder dinero = new StringBuilder();
        DecimalFormat formatter = new DecimalFormat("#,###.00");
        String formateado = formatter.format(monto);

        dinero.append(moneda);
        dinero.append(" ");
        dinero.append(formateado);
        return dinero.toString();
    }

    /**
     *
     * @param picker
     */
    private void formatoDatePicker(JXDatePicker picker) {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

        picker.setFormats(format);
    }

    /**
     *
     * @param dias
     * @param cuotas
     * @param fechaI
     * @return
     */
    public String[][] generarFechasPago(int dias, int cuotas, Date fechaI) {
        String[][] fechasPago = new String[cuotas][2];

        Calendar calendar;

        calendar = Calendar.getInstance();
        calendar.setTime(fechaI);

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formatDia = new SimpleDateFormat("EEEE");

        System.out.println("Fecha inicial: " + format.format(fechaI));
        Date dateTemp = fechaI;

        String fecha = "";
        String dia = "";
        for (int i = 0; i < cuotas; i++) {
            calendar.setTime(dateTemp);
            calendar.add(Calendar.DAY_OF_YEAR, dias);
            dateTemp = calendar.getTime();

            int diaSemana = dateTemp.getDay();

            if (diaSemana == 0) {
                calendar.add(Calendar.DAY_OF_YEAR, 1); //Si es domingo le sumamos un dia mas.                
                Date diaLunes = calendar.getTime();

                fecha = format.format(diaLunes);
                dia = formatDia.format(diaLunes);

                System.out.println("Fecha (" + (i + 1) + "): " + fecha + " dia: " + dia + "  dia semana: " + diaLunes.getDay());

            } else {
                fecha = format.format(dateTemp);
                dia = formatDia.format(dateTemp);

                System.out.println("Fecha (" + (i + 1) + "): " + fecha + " dia: " + dia + "  dia semana: " + dateTemp.getDay());

            }

            fechasPago[i][0] = fecha;
            fechasPago[i][1] = dia;
        }

        return fechasPago;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboDias;
    private javax.swing.JComboBox<String> cboDiasFrec;
    private javax.swing.JComboBox<String> cboMoneda;
    private org.jdesktop.swingx.JXDatePicker dtFechaFin;
    private org.jdesktop.swingx.JXDatePicker dtFechaInicio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator3;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstTelefono;
    private javax.swing.JPanel pnelCliente;
    private javax.swing.JPanel pnelContenedor;
    private javax.swing.JPanel pnelDatosCliente;
    private javax.swing.JPanel pnelPrestamo;
    private javax.swing.JRadioButton rbtnFemenino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JScrollPane scrollPrestamo;
    private javax.swing.JSpinner spnDiasPenalidad;
    private javax.swing.JSpinner spnFrecuencia;
    private javax.swing.JSpinner spnPlazo;
    private javax.swing.JTable tabCuotas;
    private javax.swing.JToolBar toolOpciones;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCantCuotas;
    private javax.swing.JTextField txtCantDias;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCentroLab;
    private javax.swing.JTextField txtCobro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextArea txtDireccionPrin;
    private javax.swing.JTextArea txtDireccionSec;
    private javax.swing.JFormattedTextField txtMontoCargos;
    private javax.swing.JTextField txtMontoCuota;
    private javax.swing.JFormattedTextField txtMontoInteres;
    private javax.swing.JTextField txtMontoLetras;
    private javax.swing.JFormattedTextField txtMontoPenalidad;
    private javax.swing.JFormattedTextField txtMontoPrestamo;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JFormattedTextField txtTasa;
    private javax.swing.JFormattedTextField txtTasaCargo;
    private javax.swing.JTextField txtTotalPrestamo;
    // End of variables declaration//GEN-END:variables

    private void guardarPrestamo() {
        PrestamoEntidad p = new PrestamoEntidad();
        PrestamoDAO pDao = new PrestamoDAO(con.getCon());
        
        CuotasEntidad c = new CuotasEntidad();
        CuotasDAO cDao = new CuotasDAO(con.getCon());
        
        
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat format2 = new SimpleDateFormat("dd/MM/yyyy");

        if (cliente != null) {
            p.setIdCliente(cliente.getIdCliente());
            p.setFechaInicio(format.format(dtFechaInicio.getDate()));
            p.setFechaVencimiento(format.format(dtFechaFin.getDate()));
            p.setIdPlazo(cboDias.getSelectedIndex() + 1); //Se que esta mal, pero hay poco tiempo!.. :-)
            p.setCantPeriodo(cantPlazo);
            p.setIdMoneda(idMoneda);
            p.setPlazoDias(dias);
            p.setMontoOriginal(montoPrestamo);
            p.setTasa(tasaInteres);
            p.setTasaCargo(tasaCargos);
            p.setMontoCargos(montoCargos);
            p.setMontoTotal(totalPrestamo);
            p.setCantidadCuotas(cantCuota);
            p.setMontoCuota(cuota);
            p.setIdFrecuenciaPago(cboDiasFrec.getSelectedIndex() + 1);
            p.setCantFrecuencia(cantPlazoFrec);
            p.setFrecuenciaDias(diasFrecPago);
            p.setMontoPenalidad(Double.parseDouble(txtMontoPenalidad.getText()));
            p.setDiasPenalidad((int) spnDiasPenalidad.getValue());
            p.setEstado(1);

            int id = pDao.insertarPrestamo(p);

            if (id > 0) {
                JOptionPane.showMessageDialog(prin, "Se inserto la chochada! Id:" + id, "Insertando Prestamo", JOptionPane.INFORMATION_MESSAGE);
                
                
                for(int i=0; i<tabCuotas.getRowCount();i++)
                {
                    c = new CuotasEntidad();
                    c.setIdPrestamo(id);
                    c.setPagoNumero(tabCuotas.getValueAt(i, 0).toString());
                    try {
                        c.setFecha( format.format(format2.parse(tabCuotas.getValueAt(i, 1).toString())) );
                    } catch (ParseException ex) {
                        Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("ERROR al convertir fecha: "+ex.getMessage());
                    }
                    
                    c.setDia(tabCuotas.getValueAt(i, 2).toString());
                    c.setMonto(Double.parseDouble(tabCuotas.getValueAt(i, 3).toString()));
                    c.setSaldo(Double.parseDouble(tabCuotas.getValueAt(i, 4).toString()));
                    c.setCancelado(0);
                    cDao.insertarCuota(c);
                }
                
                
                
                
                
            } else {
                JOptionPane.showMessageDialog(prin, "NO SIRVE!", "Insertando Prestamo", JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }

}
