/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loansystem.visual.panel;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import loansystem.Principal;
import loansystem.bd.Conexion;
import loansystem.dao.CargoDAO;
import loansystem.dao.PersonalDAO;
import loansystem.dao.UsuarioDAO;
import loansystem.entidad.CargoEntidad;
import loansystem.entidad.PersonalEntidad;
import loansystem.entidad.UsuarioEntidad;
import loansystem.visual.modal.BuscarPersona;

/**
 *
 * @author JChavarria
 */
public class Usuario extends javax.swing.JPanel {

    private Conexion con;
    private Principal prin;
    private boolean inact = false, passw = false, nuevo = false, save = false;

    /**
     * Creates new form Usuario
     */
    public Usuario(Conexion con, Principal prin) {
        this.con = con;
        this.prin = prin;

        initComponents();
        txtPass.setVisible(false);
        txtPass2.setVisible(false);
        lblPass2.setVisible(false);
        lblPass.setVisible(false);
        txtPass3.setVisible(false);
        lblPass3.setVisible(false);
        txtLogin.setEditable(false);
        cboEstado.setEnabled(false);
        btnPass.setEnabled(false);
        btnInact.setEnabled(false);
        btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        lblPass2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtPass2 = new javax.swing.JPasswordField();
        lblPass3 = new javax.swing.JLabel();
        txtPass3 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnBuscarPersona = new javax.swing.JButton();
        btnPass = new javax.swing.JButton();
        btnInact = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel9.setText("jLabel9");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Id:");

        jLabel1.setText("Nombre:");

        jLabel3.setText("Cargo:");

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNombre.setEditable(false);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCargo.setEditable(false);
        txtCargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de la Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLabel4.setText("Login:");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        lblPass.setText("Contraseña actual: ");

        jLabel7.setText("Estado:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        lblPass2.setText("Nueva Contraseña:");

        lblPass3.setText("Repita Contraseña:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass)
                    .addComponent(jLabel7)
                    .addComponent(lblPass2)
                    .addComponent(lblPass3)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cboEstado, 0, 147, Short.MAX_VALUE)
                        .addComponent(txtPass))
                    .addComponent(txtPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass2)
                            .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass3)
                    .addComponent(txtPass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel8.setBackground(new java.awt.Color(0, 0, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Administración de Usuarios ");
        jLabel8.setOpaque(true);
        add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/search.png"))); // NOI18N
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuscarPersona);

        btnPass.setText("Cambiar Pass");
        btnPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPass);

        btnInact.setText("Estado");
        btnInact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInact);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/save.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/cerrar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        add(jToolBar1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        // TODO add your handling code here:
        BuscarPersona bp = new BuscarPersona(prin, true, con, this);
        bp.setVisible(true);
        /*inact = false;
        passw = false;
        nuevo = false;
        save = false;*/
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnInactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactActionPerformed
        // TODO add your handling code here:
        btnGuardar.setEnabled(true);
        cboEstado.setEnabled(true);
        btnInact.setEnabled(false);
        btnPass.setEnabled(false);
        inact = true;

    }//GEN-LAST:event_btnInactActionPerformed

    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
        // TODO add your handling code here:
        btnGuardar.setEnabled(true);
        passw = true;
        inact = false;
        txtPass.setVisible(true);
        txtPass2.setVisible(true);
        txtPass3.setVisible(true);

        lblPass2.setVisible(true);
        lblPass.setVisible(true);
        lblPass3.setVisible(true);

        txtPass2.setEditable(true);
        txtPass.setEditable(true);
        txtPass3.setEditable(true);

        btnPass.setEnabled(false);
        btnPass.setEnabled(false);
        btnInact.setEnabled(false);

    }//GEN-LAST:event_btnPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        prin.removerTab(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        PersonalDAO persoDAO = new PersonalDAO(con.getCon());
        PersonalEntidad persoE = persoDAO.obtenerXPersona(Integer.parseInt(txtId.getText()));
        UsuarioDAO dao = new UsuarioDAO(con.getCon());
        UsuarioEntidad entidadUser = new UsuarioEntidad();
        entidadUser = dao.obtenerXUsuarioIdPersona(persoE.getIdPersona()); //obtiene la info de la cuenta de usuario de la persona seleccionada

        if (inact) {
            UsuarioEntidad UsuarioEnti = new UsuarioEntidad();
            if (cboEstado.getSelectedItem().equals("Activo")) {
                UsuarioEnti.setEstado(1);
            } else {
                UsuarioEnti.setEstado(0);
            }

            save = dao.updateEstadoUsuario(UsuarioEnti, entidadUser.getIdUsuario());
            if (save) {
                JOptionPane.showMessageDialog(this, "Estado actualizado exitosamente!!", "Administración de Usuarios", JOptionPane.INFORMATION_MESSAGE);
                inact = false;
                btnGuardar.setEnabled(false);
                cboEstado.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el estado", "Administración de Usuarios", JOptionPane.ERROR_MESSAGE);
            }
        }

        if (passw) {
            String passActual = txtPass.getText(); //convertir a md5
            String passNueva = txtPass2.getText();
            String passNueva2 = txtPass3.getText();

            UsuarioEntidad passEntidad = new UsuarioEntidad();
            passEntidad = dao.conv_md5(passActual);

            System.out.println("md5 es: " + passEntidad.getPass_new());
            if (passNueva.equals(passNueva2)) {
                if (passEntidad.getPass_new().equals(entidadUser.getPass())) {
                    System.out.println(passEntidad.getPass_new() + " == " + entidadUser.getPass());

                    UsuarioEntidad UsuarioEnti = new UsuarioEntidad();
                    UsuarioEnti.setPass(passNueva);
                    save = dao.updatePassUsuario(UsuarioEnti, txtLogin.getText(), passActual);

                    if (save) {
                        JOptionPane.showMessageDialog(this, "Contraseña actualizada exitosamente!!", "Administración de Usuarios", JOptionPane.INFORMATION_MESSAGE);
                        btnGuardar.setEnabled(false);
                        passw = false;
                        txtPass.setEditable(false);
                        txtPass2.setEditable(false);
                        txtPass3.setEditable(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo actualizar la contraseña", "Administración de Usuarios", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "La contraseña actual ingresada no coincide", "Administración de Usuarios", JOptionPane.ERROR_MESSAGE);
                    System.out.println(passActual + " != " + entidadUser.getPass());
                    System.out.println("---------------------------------------------");
                    System.out.println(passEntidad.getPass_new() + " != " + entidadUser.getPass());
                    passw = true;

                }
            } else {
                JOptionPane.showMessageDialog(this, "La Nueva Contraseña no coincide en su verificación", "Administración de Usuarios", JOptionPane.ERROR_MESSAGE);
            }

        }

        if (nuevo) {

            ArrayList<UsuarioEntidad> user = new ArrayList<UsuarioEntidad>();
            user = dao.obtenerUsuariosXlogiin(txtLogin.getText());
            if (user.size() > 0) {
                JOptionPane.showMessageDialog(this, "El login ingresado ya existe! Favor ingresar otro login", "Administración de Usuarios", JOptionPane.ERROR_MESSAGE);
            } else if (txtPass2.getText().equals(txtPass3.getText())) {
                UsuarioEntidad UsuarioEnti = new UsuarioEntidad();
                UsuarioEnti.setIdPersona(Integer.parseInt(txtId.getText()));
                UsuarioEnti.setLogin(txtLogin.getText());
                UsuarioEnti.setPass(txtPass2.getText());
                if (cboEstado.getSelectedItem().equals("Activo")) {
                    UsuarioEnti.setEstado(1);
                } else {
                    UsuarioEnti.setEstado(0);
                }

                save = dao.insertarUsuario(UsuarioEnti);

                if (save) {
                    JOptionPane.showMessageDialog(this, "Usuario guardado exitosamente!!", "Administración de Usuarios", JOptionPane.INFORMATION_MESSAGE);
                    btnGuardar.setEnabled(false);
                    nuevo = false;
                    txtPass.setEditable(false);
                    txtPass2.setEditable(false);
                    txtPass3.setEditable(false);
                    txtLogin.setEditable(false);
                    cboEstado.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo guardar el usuario", "Administración de Usuarios", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Contraseñas no coinciden", "Administración de Usuarios", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void limpiarForm() {
        txtCargo.setText("");
        txtId.setText("");
        txtLogin.setText("");
        txtNombre.setText("");
        txtPass.setText("");
        txtPass2.setText("");
        txtPass3.setText("");
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtPass.setVisible(false);
        txtPass2.setVisible(false);
        txtPass3.setVisible(false);
        lblPass2.setVisible(false);
        lblPass.setVisible(false);
        lblPass3.setVisible(false);
        txtLogin.setEditable(false);
        cboEstado.setEnabled(false);
        btnPass.setEnabled(false);
        btnInact.setEnabled(false);
        btnGuardar.setEnabled(false);

        limpiarForm();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    public void cargarDatosPersonal(PersonalEntidad perso) {
        limpiarForm();

        txtPass.setVisible(false);
        txtPass2.setVisible(false);
        txtPass3.setVisible(false);

        lblPass2.setVisible(false);
        lblPass.setVisible(false);
        lblPass3.setVisible(false);

        CargoDAO cargoDao = new CargoDAO(con.getCon());
        CargoEntidad cargoenti = cargoDao.obtenerCargo(perso.getIdCargo());

        //Buscar cuenta
        UsuarioEntidad usuEnti;
        UsuarioDAO daoUsu = new UsuarioDAO(con.getCon());
        usuEnti = daoUsu.obtenerXUsuarioIdPersona(perso.getIdPersona());

        if (usuEnti == null) //No hay cuenta de usuario
        {

            int resp = JOptionPane.showConfirmDialog(null, "La persona seleccionada no tiene cuenta de usuario. ¿Requiere crearle una cuenta?");
            if (JOptionPane.OK_OPTION == resp) {

                this.txtId.setText(String.valueOf(perso.getIdPersona()));
                this.txtNombre.setText(perso.getNombres().concat(" ").concat(perso.getApellidos()));
                this.txtCargo.setText(cargoenti.getCargo());

                nuevo = true;
                btnPass.setEnabled(false);
                btnInact.setEnabled(false);
                btnGuardar.setEnabled(true);

                lblPass2.setVisible(true);
                lblPass3.setVisible(true);
                txtPass3.setVisible(true);
                txtPass2.setVisible(true);

                txtPass2.setEditable(true);
                txtPass3.setEditable(true);

                cboEstado.setEnabled(true);

                txtLogin.setEditable(true);

                //Crear login
                PersonalDAO daoPerso = new PersonalDAO(con.getCon());
                PersonalEntidad enti = daoPerso.obtenerLoginPropuesto(perso.getIdPersona());
                String loginDos = null;
                String login = enti.getLogin();

                ArrayList<UsuarioEntidad> usuarioEnti;
                UsuarioEntidad usua;
                UsuarioDAO usuDAO = new UsuarioDAO(con.getCon());
                usuarioEnti = usuDAO.obtenerTodosUsuarios();

                /*   for (int i = 0; i < usuarioEnti.size(); i++) {
                    System.out.println("Login: " + login);

                    if (usuarioEnti.get(i).getLogin().contains(login)) {
                        //Login ya existe
                        usua = usuDAO.obtenerCantLogins(login);
                        loginDos = login.concat(String.valueOf(usua.getCantidad()));
                        System.out.println("Login " + loginDos + " existe");
                        txtLogin.setText(loginDos);

                    } else {
                        //Login no existe
                        System.out.println("Login " + loginDos + " No existe");
                        loginDos = login;
                        txtLogin.setText(loginDos);
                    }

                }*/
                //  txtPass3.setText("123");
                //   txtPass2.setText("123");
            } else {
            }

        } else { //Si hay cuenta de usuario
            this.txtId.setText(String.valueOf(perso.getIdPersona()));
            this.txtNombre.setText(perso.getNombres().concat(" ").concat(perso.getApellidos()));
            this.txtCargo.setText(cargoenti.getCargo());

            txtLogin.setEditable(false);
            cboEstado.setEnabled(false);
            txtLogin.setText(usuEnti.getLogin());
            if (usuEnti.getEstado() == 1) {
                cboEstado.setSelectedItem("Activo");
            } else {
                cboEstado.setSelectedItem("Inactivo");
            }

            btnPass.setEnabled(true);
            btnInact.setEnabled(true);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInact;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPass;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblPass3;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JPasswordField txtPass3;
    // End of variables declaration//GEN-END:variables
}
