/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loansystem.visual.modal;

import java.util.ArrayList;
import loansystem.Principal;
import loansystem.bd.Conexion;
import loansystem.entidad.ClienteEntidad;
import loansystem.entidad.PrestamoEntidad;
import loansystem.utilidades.MetodosGenerales;
import loansystem.visual.panel.Prestamo;

/**
 *
 * @author cgarcia
 */
public class ListaPrestamos extends javax.swing.JDialog {

    private Conexion con;
    private Principal prin;
    private Prestamo pres;
    private MetodosGenerales util;
    
    private ArrayList<PrestamoEntidad> prestamosArr;
    private ClienteEntidad cliente;

    /**
     * Creates new form ListaPrestamos
     */
    public ListaPrestamos(Principal prin, boolean modal, Conexion con, Prestamo pres) {
        super(prin, modal);
        this.prin = prin;
        this.con = con;
        this.pres = pres;

        util = new MetodosGenerales();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabPrestamos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Préstamos");
        setBackground(new java.awt.Color(255, 255, 255));

        tabPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha Inicio", "Fecha Vencimiento", "Monto Préstamo", "Plazo", "Monto Cuota", "Frecuencia Pago", "Saldo a la Fecha", "Estado", "Fecha Último Pago", "Último Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabPrestamos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabPrestamos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabPrestamosFocusGained(evt);
            }
        });
        tabPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabPrestamos);
        if (tabPrestamos.getColumnModel().getColumnCount() > 0) {
            tabPrestamos.getColumnModel().getColumn(0).setPreferredWidth(35);
        }

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/like.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Aceptar");
        btnAceptar.setFocusable(false);
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loansystem/recursos/paneles/cerrar.png"))); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.setToolTipText("Cerrar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        lblTitulo.setBackground(new java.awt.Color(0, 0, 102));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PRÉSTAMOS ACTIVOS PARA [ X ]");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo.setFocusable(false);
        lblTitulo.setIconTextGap(10);
        lblTitulo.setMaximumSize(new java.awt.Dimension(178, 20));
        lblTitulo.setMinimumSize(new java.awt.Dimension(178, 28));
        lblTitulo.setOpaque(true);
        lblTitulo.setPreferredSize(new java.awt.Dimension(178, 28));
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(1110, 394));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabPrestamosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabPrestamosFocusGained
        // TODO add your handling code here:
        // cargarFormulario();

    }//GEN-LAST:event_tabPrestamosFocusGained

    private void tabPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPrestamosMouseClicked
        // TODO add your handling code here:
        //  cargarFormulario();

    }//GEN-LAST:event_tabPrestamosMouseClicked

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int fila = 0;
        fila = tabPrestamos.getSelectedRow();
        PrestamoEntidad p = prestamosArr.get(fila);
                
        
        pres.cargarDatosCliente(cliente, p );
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabPrestamos;
    // End of variables declaration//GEN-END:variables

    /**
     * @param prestamosArr the prestamosArr to set
     */
    public void setPrestamosArr(ArrayList<PrestamoEntidad> prestamosArr) {
        this.prestamosArr = prestamosArr;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(ClienteEntidad cliente) {
        this.cliente = cliente;
    }
    
    public void cagarPrestamos(){
        lblTitulo.setText(lblTitulo.getText().replace("X", cliente.getNombres()+" "+cliente.getApellidos()) );
        
        if(prestamosArr.size()>0)
        {
            int i = 0;
            for(PrestamoEntidad p : prestamosArr)
            {
                util.agregarFila(tabPrestamos);
                tabPrestamos.setValueAt(p.getIdPrestamo(),i ,0 );
                tabPrestamos.setValueAt(p.getFechaInicio(),i ,1 );
                tabPrestamos.setValueAt(p.getFechaVencimiento(),i ,2 );
                tabPrestamos.setValueAt(p.getSimboloMoneda() +" "+ p.getMontoTotal(),i ,3 );
                tabPrestamos.setValueAt(p.getCantPeriodo() + " "+p.getPlazoPrestamo(),i ,4 );
                tabPrestamos.setValueAt(p.getSimboloMoneda() +" "+util.round(p.getMontoCuota(),2),i ,5 );
                tabPrestamos.setValueAt("Cada "+p.getCantFrecuencia() + " "+p.getFrecueciaPago()+(p.getCantFrecuencia()>0?"s":""   ) ,i ,6 );
                tabPrestamos.setValueAt(p.getSimboloMoneda() +" "+p.getSaldoActual(),i ,7 );
                tabPrestamos.setValueAt(p.getDescEstado(),i ,8);
                tabPrestamos.setValueAt(p.getFechaUltimoPago(),i ,9);
                tabPrestamos.setValueAt(p.getSimboloMoneda() +" "+p.getUltimoPago(),i ,10);
                
                i++;

                
            }
        }
        
    }
}
